Repository psu-modelworx/sweng-capstone-project, pull requests merged in 2025-07, with the labels that each got.

#124 40 provide login error messages
  proj/accounts/forms.py
  proj/accounts/urls.py
  proj/accounts/views.py
  proj/templates/base/navbar.html
  proj/templates/registration/login.html
Labels: bug_fix

#134 Overwrite .env in production using GitHub Secrets and Actions
  .github/workflows/deploy.yml
  README.md
  proj/modelworx/settings.py
Labels: bug

#137 Added django-admin-two-factor
  proj/modelworx/settings.py
  proj/modelworx/urls.py
  requirements
Labels: enhancement

#142 14 provide users insights
  proj/automodeler/helper_functions.py
  proj/automodeler/models.py
  proj/automodeler/tasks.py
  proj/automodeler/templates/automodeler/dataset_collection.html
  proj/automodeler/templates/automodeler/dataset_details.html
  proj/automodeler/templates/automodeler/model_collection.html
  proj/automodeler/urls.py
  proj/automodeler/views.py
  proj/tests/test_tasks.py
Labels: enhancement
